# Generated by Django 5.1.3 on 2024-12-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('REPLENISHMENT', 'Replenishment'), ('TRADE', 'Trade')], default='REPLENISHMENT', verbose_name='Вид транзакции'),
        ),
    ]
