# Generated by Django 5.1.3 on 2024-12-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency_from',
            field=models.CharField(default='USD', max_length=10, verbose_name='Валюта 1'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_to',
            field=models.CharField(default='USD', max_length=10, verbose_name='Валюта 2'),
        ),
    ]
