# Generated by Django 5.1.3 on 2024-12-02 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='amount_from',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Сумма валюты от'),
        ),
        migrations.AddField(
            model_name='trades',
            name='amount_to',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Сумма валюты к обмену'),
        ),
        migrations.AddField(
            model_name='trades',
            name='currency_from',
            field=models.CharField(default='USD', max_length=10, verbose_name='Валюта, которую предлагают'),
        ),
        migrations.AddField(
            model_name='trades',
            name='currency_to',
            field=models.CharField(default='USD', max_length=10, verbose_name='Валюта, которую хотят получить'),
        ),
        migrations.AddField(
            model_name='trades',
            name='trades_type',
            field=models.CharField(choices=[('CTU', 'Crypto_to_USD'), ('UTC', 'USD_to_Crypto')], default='CTU', verbose_name='Вид трейда'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_initiator', to=settings.AUTH_USER_MODEL, verbose_name='Автор трейда'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания трейда'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='other_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, принимающий трейд'),
        ),
    ]
