# Generated by Django 5.1.3 on 2024-12-02 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_clientcard_balance_in_usd'),
        ('trades', '0002_trades_amount_from_trades_amount_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='customers.clientcard', verbose_name='Карта для списания'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='amount_from',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Количество валюты'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='amount_to',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Количество валюты к обмену'),
        ),
    ]
