# Generated by Django 5.1.3 on 2024-11-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_userreaction_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
