# Generated by Django 5.1.3 on 2024-12-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.URLField(blank=True, help_text='Фото новости', null=True),
        ),
    ]
