# Generated by Django 5.1.3 on 2024-11-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcard',
            name='balance',
            field=models.JSONField(default={'BTC': 0, 'ETH': 0, 'SOL': 0, 'USDT': 0, 'XPR': 0}, help_text="Баланс по каждой криптовалюте (например: {'BTC': 0.5, 'ETH': 2}).", verbose_name='Баланс'),
        ),
    ]
