# Generated by Django 5.1.3 on 2024-11-29 22:53

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_clientcard_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcard',
            name='balance',
            field=models.JSONField(default=customers.models.set_default_balance, help_text="Баланс по каждой криптовалюте (например: {'BTC': 0.5, 'ETH': 2}).", verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='clientcard',
            name='supported_currencies',
            field=models.JSONField(default=customers.models.set_default_currencies_list, help_text="Список криптовалют (например: ['BTC', 'ETH', 'USDT']).", verbose_name='Поддерживаемые криптовалюты'),
        ),
    ]
