# Generated by Django 5.1.3 on 2024-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_clientcard_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcard',
            name='balance_in_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Баланс на карте в USD'),
        ),
    ]
