# Generated by Django 5.1.3 on 2024-12-05 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_clientcard_balance_in_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcard',
            name='balance_in_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс на карте в USD'),
        ),
    ]
