# Generated by Django 5.1.3 on 2024-12-06 22:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_clientcard_balance_in_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcard',
            name='transaction_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Комиссия за транзакции (%)'),
        ),
    ]
