# Generated by Django 5.1.3 on 2024-12-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ администратора'),
        ),
    ]
