# Generated by Django 5.1.3 on 2024-11-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('AD', 'admin'), ('US', 'user')], help_text='Роль пользователя', max_length=2),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='requested_role',
            field=models.CharField(choices=[('AD', 'admin'), ('US', 'user')], help_text='Запрашиваемая роль', max_length=2),
        ),
    ]
