# Generated by Django 5.1.3 on 2024-12-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='promo',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
