# Generated by Django 5.1.3 on 2024-12-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='promo_usage',
            field=models.IntegerField(default=0, verbose_name='Количество пользователей, которые ввели промокод'),
        ),
    ]
