# Generated by Django 5.1.3 on 2024-12-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_promo_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trades_count',
            field=models.IntegerField(default=0, verbose_name='Количество совершенных трейдов'),
        ),
    ]
