# Generated by Django 5.1.3 on 2024-12-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_promousage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_used_promo',
            field=models.BooleanField(default=False, verbose_name='Использовал ли пользователь чужой промокод'),
        ),
    ]
