# Generated by Django 5.1.3 on 2024-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_has_used_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_permanent_discount',
            field=models.BooleanField(default=False, verbose_name='Пользователь получил постоянную скидку на комиссию'),
        ),
    ]
