# Generated by Django 5.1.3 on 2024-12-16 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_has_permanent_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='promo_usage',
        ),
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=8, verbose_name='Промокод')),
                ('promo_usage', models.IntegerField(default=0, verbose_name='Количество пользователей, которые ввели промокод')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'db_table': 'Promos',
                'unique_together': {('user', 'promo_code')},
            },
        ),
        migrations.DeleteModel(
            name='PromoUsage',
        ),
    ]
